### ISSUE TITLE
Use api ?

### ISSUE THREAD

**Issue by rocket13011** [hansemannn/titanium-homekit#1]
Hello,

Already bravo for this module!
Can we have an example of how to use the api?

Thank you.

**Comment by hansemannn** [comment]
The api is 99 % named like the native API, so you should be able to follow any iOS HomeKit tutorial, e.g. http://www.xmcgraw.com/learn-how-to-create-an-ios-app-using-homekit/

**Comment by hansemannn** [comment]
Added two examples in the recent release 1.1.1, check it out!
